name: Publish Android Packages to GitHub Packages Maven

on:
  push:
    branches:
      - deploy/packages

jobs:
  publish:
    name: Publish Maven Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish purchases-hybrid-common package to GitHub Packages
        working-directory: android
        run: ./gradlew :hybridcommon:publishAllPublicationsToGitHubPackagesRepository --no-daemon --no-parallel
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
